dependencies:
  fabrique:
    import: socialgouv/kontinuous/plugins/fabrique
    dependencies:
      contrib:
        valuesCompilers:
          globalDefaults:
            options:
              mergeValues:
                buildkitServiceAddr: tcp://buildkit.socialgouv.io:1234
